# Generated by Django 4.0.4 on 2022-05-13 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('user', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Nome de Usuário')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição')),
                ('areas_interesse', models.CharField(max_length=250, verbose_name='Áreas de interesse')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iniciacao_cientifica.aluno')),
            ],
            bases=('iniciacao_cientifica.aluno',),
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('resumo', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('evento', models.CharField(max_length=250)),
                ('autores', models.ManyToManyField(to='iniciacao_cientifica.autor')),
            ],
        ),
    ]
